// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2) {
  return window['go']['app']['App']['AddLog'](arg1, arg2);
}

export function AnalyzeFile(arg1) {
  return window['go']['app']['App']['AnalyzeFile'](arg1);
}

export function AnalyzeMultiple(arg1) {
  return window['go']['app']['App']['AnalyzeMultiple'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function CheckAPIStatus() {
  return window['go']['app']['App']['CheckAPIStatus']();
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function ClearDownloadHistory() {
  return window['go']['app']['App']['ClearDownloadHistory']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function ConvertFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ConvertFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function ConvertFolder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ConvertFolder'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteHistoryRecord(arg1) {
  return window['go']['app']['App']['DeleteHistoryRecord'](arg1);
}

export function DetectSourceFromURL(arg1) {
  return window['go']['app']['App']['DetectSourceFromURL'](arg1);
}

export function DownloadArtistAssets(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadArtistAssets'](arg1, arg2, arg3);
}

export function DownloadTrack(arg1, arg2) {
  return window['go']['app']['App']['DownloadTrack'](arg1, arg2);
}

export function DownloadTrackFromTidal(arg1, arg2) {
  return window['go']['app']['App']['DownloadTrackFromTidal'](arg1, arg2);
}

export function EmbedLyricsToFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['EmbedLyricsToFile'](arg1, arg2, arg3);
}

export function ExpandDiscographyURL(arg1) {
  return window['go']['app']['App']['ExpandDiscographyURL'](arg1);
}

export function ExportFailedDownloads(arg1) {
  return window['go']['app']['App']['ExportFailedDownloads'](arg1);
}

export function FetchAndEmbedLyrics(arg1) {
  return window['go']['app']['App']['FetchAndEmbedLyrics'](arg1);
}

export function FetchAndEmbedLyricsMultiple(arg1) {
  return window['go']['app']['App']['FetchAndEmbedLyricsMultiple'](arg1);
}

export function FetchContentFromURL(arg1) {
  return window['go']['app']['App']['FetchContentFromURL'](arg1);
}

export function FetchLyrics(arg1, arg2, arg3) {
  return window['go']['app']['App']['FetchLyrics'](arg1, arg2, arg3);
}

export function FetchLyricsForFile(arg1) {
  return window['go']['app']['App']['FetchLyricsForFile'](arg1);
}

export function FetchTidalContent(arg1) {
  return window['go']['app']['App']['FetchTidalContent'](arg1);
}

export function FetchTidalPlaylist(arg1) {
  return window['go']['app']['App']['FetchTidalPlaylist'](arg1);
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetAvailableSources() {
  return window['go']['app']['App']['GetAvailableSources']();
}

export function GetCacheStats() {
  return window['go']['app']['App']['GetCacheStats']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConnectionStatus() {
  return window['go']['app']['App']['GetConnectionStatus']();
}

export function GetConversionFormats() {
  return window['go']['app']['App']['GetConversionFormats']();
}

export function GetDownloadFolder() {
  return window['go']['app']['App']['GetDownloadFolder']();
}

export function GetDownloadHistory() {
  return window['go']['app']['App']['GetDownloadHistory']();
}

export function GetDownloadHistoryFiltered(arg1) {
  return window['go']['app']['App']['GetDownloadHistoryFiltered'](arg1);
}

export function GetDownloadOptions() {
  return window['go']['app']['App']['GetDownloadOptions']();
}

export function GetDownloadQueueStatus() {
  return window['go']['app']['App']['GetDownloadQueueStatus']();
}

export function GetFFmpegInfo() {
  return window['go']['app']['App']['GetFFmpegInfo']();
}

export function GetFFmpegInstallStatus() {
  return window['go']['app']['App']['GetFFmpegInstallStatus']();
}

export function GetFileCoverArt(arg1) {
  return window['go']['app']['App']['GetFileCoverArt'](arg1);
}

export function GetFileMetadata(arg1) {
  return window['go']['app']['App']['GetFileMetadata'](arg1);
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetMatchFailures() {
  return window['go']['app']['App']['GetMatchFailures']();
}

export function GetPreferredSource() {
  return window['go']['app']['App']['GetPreferredSource']();
}

export function GetRecentAlbums(arg1) {
  return window['go']['app']['App']['GetRecentAlbums'](arg1);
}

export function GetRenameTemplates() {
  return window['go']['app']['App']['GetRenameTemplates']();
}

export function GetSldlStatus() {
  return window['go']['app']['App']['GetSldlStatus']();
}

export function GetSourceAlbum(arg1, arg2) {
  return window['go']['app']['App']['GetSourceAlbum'](arg1, arg2);
}

export function GetSourceHealth() {
  return window['go']['app']['App']['GetSourceHealth']();
}

export function GetSourcePlaylist(arg1, arg2) {
  return window['go']['app']['App']['GetSourcePlaylist'](arg1, arg2);
}

export function GetSourceTrack(arg1, arg2) {
  return window['go']['app']['App']['GetSourceTrack'](arg1, arg2);
}

export function InstallFFmpeg() {
  return window['go']['app']['App']['InstallFFmpeg']();
}

export function InstallSldl() {
  return window['go']['app']['App']['InstallSldl']();
}

export function IsConverterAvailable() {
  return window['go']['app']['App']['IsConverterAvailable']();
}

export function IsDownloaderAvailable() {
  return window['go']['app']['App']['IsDownloaderAvailable']();
}

export function IsQobuzConfigured() {
  return window['go']['app']['App']['IsQobuzConfigured']();
}

export function IsQueuePaused() {
  return window['go']['app']['App']['IsQueuePaused']();
}

export function ListDownloadedFiles() {
  return window['go']['app']['App']['ListDownloadedFiles']();
}

export function MatchPlaylistTracks(arg1) {
  return window['go']['app']['App']['MatchPlaylistTracks'](arg1);
}

export function MatchSingleTrack(arg1) {
  return window['go']['app']['App']['MatchSingleTrack'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['app']['App']['OpenConfigFolder']();
}

export function OpenDownloadFolder(arg1) {
  return window['go']['app']['App']['OpenDownloadFolder'](arg1);
}

export function OpenFLACFilesDialog() {
  return window['go']['app']['App']['OpenFLACFilesDialog']();
}

export function PauseDownloads() {
  return window['go']['app']['App']['PauseDownloads']();
}

export function PreviewRename(arg1, arg2) {
  return window['go']['app']['App']['PreviewRename'](arg1, arg2);
}

export function QueueArtistAlbum(arg1, arg2, arg3) {
  return window['go']['app']['App']['QueueArtistAlbum'](arg1, arg2, arg3);
}

export function QueueDiscographyAlbums(arg1, arg2) {
  return window['go']['app']['App']['QueueDiscographyAlbums'](arg1, arg2);
}

export function QueueDownloads(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['QueueDownloads'](arg1, arg2, arg3, arg4, arg5);
}

export function QueueQobuzDownloads(arg1, arg2, arg3) {
  return window['go']['app']['App']['QueueQobuzDownloads'](arg1, arg2, arg3);
}

export function QueueSingleDownload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['QueueSingleDownload'](arg1, arg2, arg3, arg4);
}

export function QuickAnalyze(arg1) {
  return window['go']['app']['App']['QuickAnalyze'](arg1);
}

export function RefetchFromHistory(arg1) {
  return window['go']['app']['App']['RefetchFromHistory'](arg1);
}

export function RefreshTidalEndpoints() {
  return window['go']['app']['App']['RefreshTidalEndpoints']();
}

export function RenameFiles(arg1, arg2) {
  return window['go']['app']['App']['RenameFiles'](arg1, arg2);
}

export function ResetToDefaults() {
  return window['go']['app']['App']['ResetToDefaults']();
}

export function ResumeDownloads() {
  return window['go']['app']['App']['ResumeDownloads']();
}

export function RetryAllFailed() {
  return window['go']['app']['App']['RetryAllFailed']();
}

export function RetryDownload(arg1) {
  return window['go']['app']['App']['RetryDownload'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SearchDeezer(arg1) {
  return window['go']['app']['App']['SearchDeezer'](arg1);
}

export function SearchTidal(arg1) {
  return window['go']['app']['App']['SearchTidal'](arg1);
}

export function SearchTidalAlbums(arg1) {
  return window['go']['app']['App']['SearchTidalAlbums'](arg1);
}

export function SearchTidalArtists(arg1) {
  return window['go']['app']['App']['SearchTidalArtists'](arg1);
}

export function SelectDownloadFolder() {
  return window['go']['app']['App']['SelectDownloadFolder']();
}

export function SelectFolderForConversion() {
  return window['go']['app']['App']['SelectFolderForConversion']();
}

export function SetDownloadFolder(arg1) {
  return window['go']['app']['App']['SetDownloadFolder'](arg1);
}

export function SetDownloadOptions(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['SetDownloadOptions'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetPreferredSource(arg1) {
  return window['go']['app']['App']['SetPreferredSource'](arg1);
}

export function SetSourceOrder(arg1) {
  return window['go']['app']['App']['SetSourceOrder'](arg1);
}

export function SetTidalCredentials(arg1, arg2) {
  return window['go']['app']['App']['SetTidalCredentials'](arg1, arg2);
}

export function TestSoulseekConnection(arg1, arg2) {
  return window['go']['app']['App']['TestSoulseekConnection'](arg1, arg2);
}

export function UpdateQobuzCredentials(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateQobuzCredentials'](arg1, arg2, arg3);
}

export function ValidateTidalURL(arg1) {
  return window['go']['app']['App']['ValidateTidalURL'](arg1);
}
