// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';

export function AddLog(arg1:string,arg2:string):Promise<void>;

export function AnalyzeFile(arg1:string):Promise<core.AnalysisResult>;

export function AnalyzeMultiple(arg1:Array<string>):Promise<Array<core.AnalysisResult>>;

export function CancelDownload(arg1:number):Promise<void>;

export function CheckAPIStatus():Promise<Array<main.EndpointStatus>>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearDownloadHistory():Promise<void>;

export function ClearLogs():Promise<void>;

export function ConvertFiles(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<Array<core.ConversionResult>>;

export function ConvertFolder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<Array<core.ConversionResult>>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteHistoryRecord(arg1:number):Promise<void>;

export function DetectSourceFromURL(arg1:string):Promise<Record<string, any>>;

export function DownloadArtistAssets(arg1:string,arg2:string,arg3:string):Promise<number>;

export function DownloadTrack(arg1:number,arg2:string):Promise<core.DownloadResult>;

export function DownloadTrackFromTidal(arg1:core.TidalTrack,arg2:string):Promise<core.DownloadResult>;

export function EmbedLyricsToFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportFailedDownloads(arg1:string):Promise<string>;

export function FetchAndEmbedLyrics(arg1:string):Promise<core.Lyrics>;

export function FetchAndEmbedLyricsMultiple(arg1:Array<string>):Promise<Array<Record<string, any>>>;

export function FetchContentFromURL(arg1:string):Promise<Record<string, any>>;

export function FetchLyrics(arg1:string,arg2:string,arg3:number):Promise<core.Lyrics>;

export function FetchLyricsForFile(arg1:string):Promise<core.Lyrics>;

export function FetchTidalContent(arg1:string):Promise<Record<string, any>>;

export function FetchTidalPlaylist(arg1:string):Promise<core.TidalPlaylist>;

export function GetAppVersion():Promise<string>;

export function GetAvailableSources():Promise<Array<core.SourceInfo>>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetConfig():Promise<core.Config>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetConversionFormats():Promise<Array<core.ConversionFormat>>;

export function GetDownloadFolder():Promise<string>;

export function GetDownloadHistory():Promise<Array<core.DownloadRecord>>;

export function GetDownloadHistoryFiltered(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetDownloadOptions():Promise<Record<string, any>>;

export function GetDownloadQueueStatus():Promise<Record<string, any>>;

export function GetFFmpegInfo():Promise<Record<string, any>>;

export function GetFFmpegInstallStatus():Promise<Record<string, any>>;

export function GetFileCoverArt(arg1:string):Promise<Record<string, string>>;

export function GetFileMetadata(arg1:string):Promise<core.FLACMetadata>;

export function GetLogs():Promise<Array<core.LogEntry>>;

export function GetMatchFailures():Promise<Array<core.MatchFailure>>;

export function GetPreferredSource():Promise<string>;

export function GetRenameTemplates():Promise<Array<Record<string, string>>>;

export function GetSourceAlbum(arg1:string,arg2:string):Promise<core.SourceAlbum>;

export function GetSourcePlaylist(arg1:string,arg2:string):Promise<core.SourcePlaylist>;

export function GetSourceTrack(arg1:string,arg2:string):Promise<core.SourceTrack>;

export function InstallFFmpeg():Promise<void>;

export function IsConverterAvailable():Promise<boolean>;

export function IsDownloaderAvailable():Promise<boolean>;

export function IsQobuzConfigured():Promise<boolean>;

export function IsQueuePaused():Promise<boolean>;

export function ListDownloadedFiles():Promise<Array<core.DownloadedFileInfo>>;

export function MatchPlaylistTracks(arg1:Array<core.TidalTrack>):Promise<Array<core.MatchResult>>;

export function MatchSingleTrack(arg1:core.TidalTrack):Promise<core.MatchResult>;

export function OpenConfigFolder():Promise<void>;

export function OpenDownloadFolder(arg1:string):Promise<void>;

export function OpenFLACFilesDialog():Promise<Array<string>>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function PauseDownloads():Promise<boolean>;

export function PreviewRename(arg1:Array<string>,arg2:string):Promise<Array<core.RenamePreview>>;

export function QueueArtistAlbum(arg1:string,arg2:string,arg3:string):Promise<number>;

export function QueueDownloads(arg1:Array<core.TidalTrack>,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function QueueQobuzDownloads(arg1:Array<core.SourceTrack>,arg2:string,arg3:string):Promise<number>;

export function QueueSingleDownload(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function QuickAnalyze(arg1:string):Promise<core.AnalysisResult>;

export function RefetchFromHistory(arg1:string):Promise<Record<string, any>>;

export function RenameFiles(arg1:Array<string>,arg2:string):Promise<Array<core.RenameResult>>;

export function ResetToDefaults():Promise<core.Config>;

export function ResumeDownloads():Promise<boolean>;

export function RetryAllFailed():Promise<number>;

export function RetryDownload(arg1:number):Promise<void>;

export function SaveConfig(arg1:core.Config):Promise<void>;

export function SearchTidal(arg1:string):Promise<Array<core.TidalTrack>>;

export function SearchTidalAlbums(arg1:string):Promise<Array<core.TidalAlbum>>;

export function SearchTidalArtists(arg1:string):Promise<Array<core.TidalArtist>>;

export function SelectDownloadFolder():Promise<string>;

export function SelectFolderForConversion():Promise<Array<string>>;

export function SetDownloadFolder(arg1:string):Promise<void>;

export function SetDownloadOptions(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean,arg6:boolean):Promise<void>;

export function SetPreferredSource(arg1:string):Promise<void>;

export function SetTidalCredentials(arg1:string,arg2:string):Promise<void>;

export function UpdateQobuzCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ValidateTidalURL(arg1:string):Promise<Record<string, any>>;
