// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLog(arg1, arg2) {
  return window['go']['main']['App']['AddLog'](arg1, arg2);
}

export function AnalyzeFile(arg1) {
  return window['go']['main']['App']['AnalyzeFile'](arg1);
}

export function AnalyzeMultiple(arg1) {
  return window['go']['main']['App']['AnalyzeMultiple'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ConvertFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConvertFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeleteHistoryRecord(arg1) {
  return window['go']['main']['App']['DeleteHistoryRecord'](arg1);
}

export function DetectSourceFromURL(arg1) {
  return window['go']['main']['App']['DetectSourceFromURL'](arg1);
}

export function DownloadTrack(arg1, arg2) {
  return window['go']['main']['App']['DownloadTrack'](arg1, arg2);
}

export function DownloadTrackFromTidal(arg1, arg2) {
  return window['go']['main']['App']['DownloadTrackFromTidal'](arg1, arg2);
}

export function EmbedLyricsToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['EmbedLyricsToFile'](arg1, arg2, arg3);
}

export function FetchAndEmbedLyrics(arg1) {
  return window['go']['main']['App']['FetchAndEmbedLyrics'](arg1);
}

export function FetchAndEmbedLyricsMultiple(arg1) {
  return window['go']['main']['App']['FetchAndEmbedLyricsMultiple'](arg1);
}

export function FetchContentFromURL(arg1) {
  return window['go']['main']['App']['FetchContentFromURL'](arg1);
}

export function FetchLyrics(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchLyrics'](arg1, arg2, arg3);
}

export function FetchLyricsForFile(arg1) {
  return window['go']['main']['App']['FetchLyricsForFile'](arg1);
}

export function FetchTidalContent(arg1) {
  return window['go']['main']['App']['FetchTidalContent'](arg1);
}

export function FetchTidalPlaylist(arg1) {
  return window['go']['main']['App']['FetchTidalPlaylist'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAvailableSources() {
  return window['go']['main']['App']['GetAvailableSources']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetConversionFormats() {
  return window['go']['main']['App']['GetConversionFormats']();
}

export function GetDownloadFolder() {
  return window['go']['main']['App']['GetDownloadFolder']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetDownloadHistoryFiltered(arg1) {
  return window['go']['main']['App']['GetDownloadHistoryFiltered'](arg1);
}

export function GetDownloadOptions() {
  return window['go']['main']['App']['GetDownloadOptions']();
}

export function GetDownloadQueueStatus() {
  return window['go']['main']['App']['GetDownloadQueueStatus']();
}

export function GetFFmpegInfo() {
  return window['go']['main']['App']['GetFFmpegInfo']();
}

export function GetFileCoverArt(arg1) {
  return window['go']['main']['App']['GetFileCoverArt'](arg1);
}

export function GetFileMetadata(arg1) {
  return window['go']['main']['App']['GetFileMetadata'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMatchFailures() {
  return window['go']['main']['App']['GetMatchFailures']();
}

export function GetPreferredSource() {
  return window['go']['main']['App']['GetPreferredSource']();
}

export function GetRenameTemplates() {
  return window['go']['main']['App']['GetRenameTemplates']();
}

export function GetSourceAlbum(arg1, arg2) {
  return window['go']['main']['App']['GetSourceAlbum'](arg1, arg2);
}

export function GetSourcePlaylist(arg1, arg2) {
  return window['go']['main']['App']['GetSourcePlaylist'](arg1, arg2);
}

export function GetSourceTrack(arg1, arg2) {
  return window['go']['main']['App']['GetSourceTrack'](arg1, arg2);
}

export function IsConverterAvailable() {
  return window['go']['main']['App']['IsConverterAvailable']();
}

export function IsDownloaderAvailable() {
  return window['go']['main']['App']['IsDownloaderAvailable']();
}

export function IsQobuzConfigured() {
  return window['go']['main']['App']['IsQobuzConfigured']();
}

export function IsQueuePaused() {
  return window['go']['main']['App']['IsQueuePaused']();
}

export function ListDownloadedFiles() {
  return window['go']['main']['App']['ListDownloadedFiles']();
}

export function MatchPlaylistTracks(arg1) {
  return window['go']['main']['App']['MatchPlaylistTracks'](arg1);
}

export function MatchSingleTrack(arg1) {
  return window['go']['main']['App']['MatchSingleTrack'](arg1);
}

export function OpenDownloadFolder(arg1) {
  return window['go']['main']['App']['OpenDownloadFolder'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function PauseDownloads() {
  return window['go']['main']['App']['PauseDownloads']();
}

export function PreviewRename(arg1, arg2) {
  return window['go']['main']['App']['PreviewRename'](arg1, arg2);
}

export function QueueDownloads(arg1, arg2, arg3) {
  return window['go']['main']['App']['QueueDownloads'](arg1, arg2, arg3);
}

export function QueueSingleDownload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueueSingleDownload'](arg1, arg2, arg3, arg4);
}

export function QuickAnalyze(arg1) {
  return window['go']['main']['App']['QuickAnalyze'](arg1);
}

export function RefetchFromHistory(arg1) {
  return window['go']['main']['App']['RefetchFromHistory'](arg1);
}

export function RenameFiles(arg1, arg2) {
  return window['go']['main']['App']['RenameFiles'](arg1, arg2);
}

export function ResetToDefaults() {
  return window['go']['main']['App']['ResetToDefaults']();
}

export function ResumeDownloads() {
  return window['go']['main']['App']['ResumeDownloads']();
}

export function RetryAllFailed() {
  return window['go']['main']['App']['RetryAllFailed']();
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchTidal(arg1) {
  return window['go']['main']['App']['SearchTidal'](arg1);
}

export function SelectDownloadFolder() {
  return window['go']['main']['App']['SelectDownloadFolder']();
}

export function SetDownloadFolder(arg1) {
  return window['go']['main']['App']['SetDownloadFolder'](arg1);
}

export function SetDownloadOptions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetDownloadOptions'](arg1, arg2, arg3, arg4);
}

export function SetPreferredSource(arg1) {
  return window['go']['main']['App']['SetPreferredSource'](arg1);
}

export function SetTidalCredentials(arg1, arg2) {
  return window['go']['main']['App']['SetTidalCredentials'](arg1, arg2);
}

export function UpdateQobuzCredentials(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateQobuzCredentials'](arg1, arg2, arg3);
}

export function ValidateTidalURL(arg1) {
  return window['go']['main']['App']['ValidateTidalURL'](arg1);
}
