// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddLog(arg1:string,arg2:string):Promise<void>;

export function AnalyzeFile(arg1:string):Promise<backend.AnalysisResult>;

export function AnalyzeMultiple(arg1:Array<string>):Promise<Array<backend.AnalysisResult>>;

export function CancelDownload(arg1:number):Promise<void>;

export function ClearDownloadHistory():Promise<void>;

export function ClearLogs():Promise<void>;

export function ConvertFiles(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<Array<backend.ConversionResult>>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteHistoryRecord(arg1:number):Promise<void>;

export function DetectSourceFromURL(arg1:string):Promise<Record<string, any>>;

export function DownloadTrack(arg1:number,arg2:string):Promise<backend.DownloadResult>;

export function DownloadTrackFromTidal(arg1:backend.TidalTrack,arg2:string):Promise<backend.DownloadResult>;

export function EmbedLyricsToFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FetchAndEmbedLyrics(arg1:string):Promise<backend.Lyrics>;

export function FetchAndEmbedLyricsMultiple(arg1:Array<string>):Promise<Array<Record<string, any>>>;

export function FetchContentFromURL(arg1:string):Promise<Record<string, any>>;

export function FetchLyrics(arg1:string,arg2:string,arg3:number):Promise<backend.Lyrics>;

export function FetchLyricsForFile(arg1:string):Promise<backend.Lyrics>;

export function FetchTidalContent(arg1:string):Promise<Record<string, any>>;

export function FetchTidalPlaylist(arg1:string):Promise<backend.TidalPlaylist>;

export function GetAppVersion():Promise<string>;

export function GetAvailableSources():Promise<Array<backend.SourceInfo>>;

export function GetCacheStats():Promise<Record<string, any>>;

export function GetConfig():Promise<backend.Config>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetConversionFormats():Promise<Array<backend.ConversionFormat>>;

export function GetDownloadFolder():Promise<string>;

export function GetDownloadHistory():Promise<Array<backend.DownloadRecord>>;

export function GetDownloadHistoryFiltered(arg1:Record<string, any>):Promise<Record<string, any>>;

export function GetDownloadOptions():Promise<Record<string, any>>;

export function GetDownloadQueueStatus():Promise<Record<string, any>>;

export function GetFFmpegInfo():Promise<Record<string, any>>;

export function GetFileCoverArt(arg1:string):Promise<Record<string, string>>;

export function GetFileMetadata(arg1:string):Promise<backend.FLACMetadata>;

export function GetLogs():Promise<Array<backend.LogEntry>>;

export function GetMatchFailures():Promise<Array<backend.MatchFailure>>;

export function GetPreferredSource():Promise<string>;

export function GetRenameTemplates():Promise<Array<Record<string, string>>>;

export function GetSourceAlbum(arg1:string,arg2:string):Promise<backend.SourceAlbum>;

export function GetSourcePlaylist(arg1:string,arg2:string):Promise<backend.SourcePlaylist>;

export function GetSourceTrack(arg1:string,arg2:string):Promise<backend.SourceTrack>;

export function IsConverterAvailable():Promise<boolean>;

export function IsDownloaderAvailable():Promise<boolean>;

export function IsQobuzConfigured():Promise<boolean>;

export function IsQueuePaused():Promise<boolean>;

export function ListDownloadedFiles():Promise<Array<backend.DownloadedFileInfo>>;

export function MatchPlaylistTracks(arg1:Array<backend.TidalTrack>):Promise<Array<backend.MatchResult>>;

export function MatchSingleTrack(arg1:backend.TidalTrack):Promise<backend.MatchResult>;

export function OpenDownloadFolder(arg1:string):Promise<void>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function PauseDownloads():Promise<boolean>;

export function PreviewRename(arg1:Array<string>,arg2:string):Promise<Array<backend.RenamePreview>>;

export function QueueDownloads(arg1:Array<backend.TidalTrack>,arg2:string,arg3:string):Promise<number>;

export function QueueSingleDownload(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function QuickAnalyze(arg1:string):Promise<backend.AnalysisResult>;

export function RefetchFromHistory(arg1:string):Promise<Record<string, any>>;

export function RenameFiles(arg1:Array<string>,arg2:string):Promise<Array<backend.RenameResult>>;

export function ResetToDefaults():Promise<backend.Config>;

export function ResumeDownloads():Promise<boolean>;

export function RetryAllFailed():Promise<number>;

export function RetryDownload(arg1:number):Promise<void>;

export function SaveConfig(arg1:backend.Config):Promise<void>;

export function SearchTidal(arg1:string):Promise<Array<backend.TidalTrack>>;

export function SelectDownloadFolder():Promise<string>;

export function SetDownloadFolder(arg1:string):Promise<void>;

export function SetDownloadOptions(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function SetPreferredSource(arg1:string):Promise<void>;

export function SetTidalCredentials(arg1:string,arg2:string):Promise<void>;

export function UpdateQobuzCredentials(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ValidateTidalURL(arg1:string):Promise<Record<string, any>>;
